In [30]:
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np

In [57]:
###This is just a random dataframe to demonstrate log regression
X = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))
###singe column of 0s and 1s to represent what the PHA dummy column will look like
y = np.array(np.random.randint(0,2,size=100,))##here i used numpy array, but a column from a dataframe will work the same

In [58]:
X.head()

A   B   C   D
0   7  27  93  39
1  46  45  41   2
2  45  78  96  28
3  77  89  63  49
4  99  75  70  27

In [59]:
y

array([0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1])

In [60]:
model = LogisticRegression()

In [61]:
model = model.fit(X,y)
model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [62]:
model.coef_

array([[-0.00287917, -0.00100553, -0.0168373 ,  0.00539024]])

In [63]:
model.intercept_

array([ 0.11200642])

In [64]:
newX = np.array(np.random.randint(0,2,size=4)).reshape(-1,4) ##you can probably ignore the reshape part

In [65]:
model.predict(newX)

array([1])

In [69]:
print(model.classes_)
print(model.predict_proba(newX)) ##0 has .47 chance, 1 has .528 chance

[0 1]
[[ 0.47140187  0.52859813]]
